const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
test('cloud workspace persists shared projects, enforces invitations, uploads directly and accounts durable jobs', async () => {
  const f = await require('./cloud-fixture')();
  try {
    assert.equal((await f.api('/api/projects')).status, 401);
    assert.equal((await f.api('/uploads/any/file.mp4')).status, 401);
    const logged = await f.api('/api/auth/login', { email:'owner@example.com', password:'owner-test-password' });
    assert.equal(logged.status, 200); const owner = logged.cookie;
    assert.match(logged.headers.get('set-cookie'), /HttpOnly/); assert.match(logged.headers.get('set-cookie'), /Secure/);
    assert.equal((await f.api('/api/projects', { name:'denied' }, owner, 'POST', { Origin:'https://attacker.test' })).status, 403);
    const invite = await f.api('/api/members/invites', { email:'friend@example.com' }, owner);
    const token = invite.data.path.split('=')[1];
    const joined = await f.api('/api/auth/accept', { token, name:'朋友', password:'friend-test-password' });
    assert.equal(joined.status, 201); const friend = joined.cookie;
    assert.equal((await f.api('/api/auth/accept', { token, name:'再次', password:'friend-test-password' })).status, 400);
    assert.equal((await f.api('/api/members', null, friend)).status, 403);
    const projects = await Promise.all(Array.from({ length: 6 }, (_, i) => f.api('/api/projects', { name:'项目' + i }, i % 2 ? friend : owner)));
    projects.forEach(p => assert.equal(p.status, 201));
    assert.equal((await f.api('/api/projects', null, friend)).data.length, 6);
    const project = projects[0].data;
    const start = await f.api('/api/uploads/init', { projectId: project.id, file:{ name:'movie.mp4', size:9 * 1024 * 1024 } }, owner);
    assert.equal(start.status, 201); assert.equal(start.data.urls.length, 2);
    assert.equal((await f.api(`/api/uploads/${start.data.id}/complete`, {}, friend)).status, 404);
    assert.equal((await f.api(`/api/uploads/${start.data.id}/complete`, {}, owner)).status, 400);
    for (let i=0;i<2;i++) assert.equal((await fetch(start.data.urls[i], { method:'PUT', body:Buffer.alloc((i ? 1 : 8) * 1024 * 1024, i) })).status, 200);
    assert.equal((await f.api(`/api/uploads/${start.data.id}/complete`, {}, owner)).status, 200);
    const asset = await f.api(`/api/uploads/${start.data.id}/attach`, { x:12,y:34 }, owner);
    assert.equal(asset.status, 201); assert.equal(asset.data.size, 9 * 1024 * 1024);
    const repeated = await f.api(`/api/uploads/${start.data.id}/attach`, {}, owner);
    assert.equal(repeated.data.id, asset.data.id);
    const mediaResponse = await fetch(f.base + asset.data.url, { headers:{ Cookie:friend }, redirect:'manual' });
    assert.equal(mediaResponse.status, 302);
    const download = await f.api(`/api/nodes/${asset.data.id}/download?link=1`, null, friend);
    assert.equal((await fetch(download.data.url)).status, 200);
    const created = await f.api(`/api/projects/${project.id}/video-nodes`, {}, friend);
    const node = created.data;
    await f.api(`/api/nodes/${node.id}`, { generation:{ prompt:'mountain lake', count:2, method:'text' } }, friend, 'PATCH');
    assert.equal((await f.api(`/api/nodes/${node.id}/generate`, {}, friend)).status, 200);
    assert.equal(f.requests.length, 0, 'paid requests are handled by durable worker, not request handler');
    assert.equal((await f.api(`/api/nodes/${node.id}/generate`, {}, owner)).status, 409);
    await f.jobs.work();
    assert.equal(f.requests.length, 2);
    await f.store.transaction(() => { for (const j of f.store.state.jobs) j.nextAt = 0; f.store.save(); });
    await f.jobs.work();
    const result = await f.api(`/api/nodes/${node.id}/generation`, null, friend);
    assert.equal(result.data.generation.status, 'complete');
    assert.equal(result.data.generation.storageStatus, 'ready');
    assert.ok(result.data.generation.outputUrl.startsWith('/uploads/'));
    const report = await f.api('/api/usage', null, friend);
    assert.equal(report.data.records.length, 2); assert.equal(report.data.records[0].userId, joined.data.id);
    assert.equal(report.data.records[0].usage.total_tokens, 123);
    assert.equal((await f.api('/api/usage', null, owner)).data.records.length, 2);
    const month = report.data.month;
    assert.equal((await f.api('/api/usage/bill', { month, amount:10.01, userIds:[logged.data.id,joined.data.id] }, owner,'PUT')).status, 200);
    assert.equal((await f.api('/api/usage', null, friend)).data.shares.reduce((n,s) => n+s.cents,0), 1001);
    await f.api(`/api/nodes/${node.id}`, null, friend, 'DELETE');
    assert.equal((await f.api('/api/usage', null, friend)).data.records.length, 2, 'deleting nodes preserves billing history');
    // A failed queue does not submit a paid request or leave an unrecoverable busy node.
    const second = (await f.api(`/api/projects/${project.id}/video-nodes`, {}, owner)).data;
    await f.api(`/api/nodes/${second.id}`, { generation:{ prompt:'second', method:'text' } }, owner, 'PATCH');
    await f.store.transaction(() => { f.store.state.wake=null; f.store.save(); });
    f.setQueueFailure(true);
    assert.equal((await f.api(`/api/nodes/${second.id}/generate`, {}, owner)).status, 503);
    assert.equal(f.requests.length,2);
    f.setQueueFailure(false);
    await f.api(`/api/nodes/${second.id}/generate`, {}, owner); f.setSubmitFailure(true);
    await f.jobs.work(); await f.jobs.work();
    assert.equal(f.requests.length,3, 'uncertain paid POST is not automatically repeated');
    assert.equal((await f.api(`/api/nodes/${second.id}/generation`, null, owner)).data.generation.status,'failed');
    assert.equal((await f.api('/api/internal/jobs', {}, owner)).status,401);
    const wake = await f.store.transaction(() => f.store.state.wake);
    const body = { wakeId:wake.id };
    const encode = x => Buffer.from(JSON.stringify(x)).toString('base64url');
    const input = encode({alg:'HS256',typ:'JWT'}) + '.' + encode({ iss:'Upstash', sub:'https://canvas.test/api/internal/jobs', exp:Math.floor(Date.now()/1000)+60, nbf:Math.floor(Date.now()/1000)-1, body:crypto.createHash('sha256').update(JSON.stringify(body)).digest('base64url') });
    const signature = input + '.' + crypto.createHmac('sha256','test-signing-key').update(input).digest('base64url');
    assert.equal((await f.api('/api/internal/jobs', body, null, 'POST', {'upstash-signature':signature})).status,200);
    f.setSubmitFailure(false);
    await f.api(`/api/nodes/${second.id}/generate`, {}, owner); await f.jobs.work();
    await f.store.transaction(() => { const j=f.store.state.jobs.at(-1);j.failures=19;j.nextAt=0;f.store.save(); });
    f.setPollFailure(true); await f.jobs.work();
    assert.equal((await f.api('/api/storage',null,owner)).data.failed,1);
    f.setPollFailure(false);
    assert.equal((await f.api('/api/storage/sync',{},owner)).status,202);
    await f.jobs.work();
    assert.equal((await f.api(`/api/nodes/${second.id}/generation`,null,owner)).data.generation.storageStatus,'ready');
    const ownerTasks=f.requests.length;
    const snapshot=(await f.api(`/api/projects/${project.id}`,null,owner)).data;
    const generated=snapshot.nodes.find(n=>n.id===second.id);
    generated.generation.status='generating';generated.generation.jobId='forged-provider-id';generated.generation.jobs=[{index:0,jobId:'forged-provider-id',status:'generating'}];
    await f.api(`/api/projects/${project.id}/state`,{nodes:snapshot.nodes,edges:snapshot.edges},owner,'PUT');
    assert.equal((await f.api(`/api/nodes/${second.id}/generation`,null,owner)).data.generation.status,'complete');
    assert.equal(f.requests.length,ownerTasks);
    const anotherFriendSession=(await f.api('/api/auth/login',{email:'friend@example.com',password:'friend-test-password'})).cookie;
    const changed=await f.api('/api/auth/password',{currentPassword:'friend-test-password',password:'changed-friend-password'},friend);
    assert.equal(changed.status,200);
    assert.equal((await f.api('/api/projects',null,anotherFriendSession)).status,401);
    await f.api(`/api/members/${joined.data.id}`, { disabled:true }, owner, 'PATCH');
    assert.equal((await f.api('/api/projects', null, friend)).status,401);
    // Database content is reloadable through a different store instance; credentials stay private.
    const createStore = require('../state-store');
    const reloaded = createStore({ pool:f.pool });
    await reloaded.transaction(() => { assert.equal(reloaded.state.projects.length,6); assert.equal(reloaded.state.cloudRecords[asset.data.url].status,'ready'); });
    const serialized = JSON.stringify((await f.api('/api/members',null,owner)).data);
    assert.ok(!serialized.includes('passwordHash')); assert.ok(!serialized.includes('canvas_session'));
  } finally { await f.close(); }
});
